USE WAREHOUSE MSBA_PROJECT_WH;
USE DATABASE NYC_311_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE STAGE GCP_PARQUET_STAGE FILE_FORMAT = (TYPE = 'PARQUET');

DROP TABLE IF EXISTS FACT_COMPLAINTS;
DROP TABLE IF EXISTS DIM_PROPERTY;
DROP TABLE IF EXISTS DIM_COMPLAINT;


CREATE TABLE DIM_PROPERTY (
    BBL_ID NUMBER PRIMARY KEY,
    BOROUGH TEXT,
    ZIP_CODE TEXT,
    BUILDING_CLASS TEXT,
    LAND_USE NUMBER,
    YEAR_BUILT NUMBER,
    NUM_FLOORS REAL,
    BUILDING_AREA NUMBER,
    OWNER_NAME TEXT
);


CREATE TABLE DIM_COMPLAINT (
    COMPLAINT_TYPE TEXT PRIMARY KEY,
    DESCRIPTOR TEXT
);


CREATE TABLE FACT_COMPLAINTS (
    UNIQUE_KEY NUMBER,        
    BBL_ID NUMBER,
    DATE_ID DATE,
    COMPLAINT_TYPE TEXT,
    STATUS TEXT,
    LATITUDE REAL,
    LONGITUDE REAL,
    FOREIGN KEY (BBL_ID) REFERENCES DIM_PROPERTY(BBL_ID)
);


INSERT INTO DIM_PROPERTY
SELECT DISTINCT 
    $1:bbl::NUMBER, 
    $1:borough::TEXT, 
    $1:building_zip::TEXT, 
    $1:building_class::TEXT, 
    $1:land_use::NUMBER, 
    $1:year_built::NUMBER, 
    $1:num_floors::REAL, 
    $1:building_area::NUMBER, 
    $1:owner_name::TEXT
FROM @GCP_PARQUET_STAGE;


INSERT INTO DIM_COMPLAINT
SELECT DISTINCT 
    $1:complaint_type::TEXT, 
    $1:descriptor::TEXT
FROM @GCP_PARQUET_STAGE;


COPY INTO FACT_COMPLAINTS FROM (
  SELECT 
    $1:unique_key::NUMBER,  
    $1:bbl::NUMBER, 
    TO_DATE(TO_TIMESTAMP_NTZ($1:created_date::TEXT)),
    $1:complaint_type::TEXT, 
    $1:status::TEXT, 
    $1:latitude::REAL, 
    $1:longitude::REAL
  FROM @GCP_PARQUET_STAGE
);
